imageName: <image name> (mandatory)
runArgs: <arguments passed to docker run command, e.g. "-p 3000:3000">
username: <username/folder on docker.io or folder on repo>
#repoUrl: <repo url if private repo, will use docker.io if not specified>
