imageName: <image name> (mandatory)
runArgs: <arguments passed to docker run command, e.g. "-p 3000:3000">
repoFolder: <folder on repo or username on docker.io>
#repoUrl: <repo url if private repo, will use docker.io if not specified>
